patterns = {
    "phee": {
        "Adverse_event": [
            "Combination_Drug",
            "Effect",
            "Subject",
            "Subject_Age",
            "Subject_Disorder",
            "Subject_Gender",
            "Subject_Population",
            "Subject_Race",
            "Treatment",
            "Treatment_Disorder",
            "Treatment_Dosage",
            "Treatment_Drug",
            "Treatment_Duration",
            "Treatment_Freq",
            "Treatment_Route",
            "Treatment_Time_elapsed",
          ],
        "Potential_therapeutic_event": [
            "Combination_Drug",
            "Effect",
            "Subject",
            "Subject_Age",
            "Subject_Disorder",
            "Subject_Gender",
            "Subject_Population",
            "Subject_Race",
            "Treatment",
            "Treatment_Disorder",
            "Treatment_Dosage",
            "Treatment_Drug",
            "Treatment_Duration",
            "Treatment_Freq",
            "Treatment_Route",
            "Treatment_Time_elapsed",
          ],
    },
    "casie": {
        "Attack:Databreach": [
            "Attack-Pattern",
            "Attacker",
            "Compromised-Data",
            "Damage-Amount",
            "Number-of-Data",
            "Number-of-Victim",
            "Place",
            "Purpose",
            "Time",
            "Tool",
            "Victim"
        ],
        "Attack:Phishing": [
            "Attack-Pattern",
            "Attacker",
            "Damage-Amount",
            "Place",
            "Purpose",
            "Time",
            "Tool",
            "Trusted-Entity",
            "Victim",
        ],
        "Attack:Ransom": [
            "Attack-Pattern",
            "Attacker",
            "Damage-Amount",
            "Payment-Method",
            "Place",
            "Price",
            "Time",
            "Tool",
            "Victim",
        ],
        "Vulnerability-related:DiscoverVulnerability": [
            "CVE",
            "Capabilities",
            "Discoverer",
            "Supported_Platform",
            "Time",
            "Vulnerability",
            "Vulnerable_System",
            "Vulnerable_System_Owner",
            "Vulnerable_System_Version",
        ],
        "Vulnerability-related:PatchVulnerability": [
            "CVE",
            "Issues-Addressed",
            "Patch",
            "Patch-Number",
            "Releaser",
            "Supported_Platform",
            "Time",
            "Vulnerability",
            "Vulnerable_System",
            "Vulnerable_System_Version",
        ],
    },
}
event_description = {
    "phee": {
        "Adverse_event": {
            "event description": "combination drug causes a harmful effect on the subject and treatment treat the effect.",
        },
        "Potential_therapeutic_event": {
            "event description": "combination drug is treatment and brings a potential beneﬁcial effect on the subject.",
        },
    },
    "casie": {
        "Attack:Databreach": {
            "event description": "Attacker used Tool to compromise a system and remove Victim Compromised-Data at Time in Place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "Attack Pattern {ROLE_Attack-Pattern} Attacker {ROLE_Attacker} Compromised Data {ROLE_Compromised-Data} Damage Amount {ROLE_Damage-Amount} Number of Data {ROLE_Number-of-Data} Number of Victim {ROLE_Number-of-Victim} Place {ROLE_Place} Purpose {ROLE_Purpose} Time {ROLE_Time} Tool {ROLE_Tool} Victim {ROLE_Victim}",
            "valid roles": ['Attack-Pattern', 'Attacker', 'Compromised-Data', 'Damage-Amount', 'Number-of-Data', 'Number-of-Victim', 'Place', 'Purpose', 'Time', 'Tool', 'Victim'],
        },
        "Attack:Phishing": {
            "event description": "For Purpose,Attacker imitates Victim to get Victim to access Trusted-Entity at Time in Place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "Attack Pattern {ROLE_Attack-Pattern} Attacker {ROLE_Attacker} Damage Amount {ROLE_Damage-Amount} Place {ROLE_Place} Purpose {ROLE_Purpose} Time {ROLE_Time} Tool {ROLE_Tool} Trusted Entity {ROLE_Trusted-Entity} Victim {ROLE_Victim}",
            "valid roles": ['Attack-Pattern', 'Attacker', 'Damage-Amount', 'Place', 'Purpose', 'Time', 'Tool', 'Trusted-Entity', 'Victim'],
        },
        "Attack:Ransom": {
            "event type": "Attack:Ransom",
            "keywords": [],
            "event description": "Attacker encrypts Victim data and will only decrypt the data for a payment at Time in Place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "Attack Pattern {ROLE_Attack-Pattern} Attacker {ROLE_Attacker} Damage Amount {ROLE_Damage-Amount} Payment Method {ROLE_Payment-Method} Place {ROLE_Place} Price {ROLE_Price} Time {ROLE_Time} Tool {ROLE_Tool} Victim {ROLE_Victim}",
            "valid roles": ['Attack-Pattern', 'Attacker', 'Damage-Amount', 'Payment-Method', 'Place', 'Price', 'Time', 'Tool', 'Victim'],
        },
        "Vulnerability-related:DiscoverVulnerability": {
            "event type": "Vulnerability-related:DiscoverVulnerability",
            "keywords": [],
            "event description": "Discoverer finds Vulnerability at Time in Place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "CVE {ROLE_CVE} Capabilities {ROLE_Capabilities} Discoverer {ROLE_Discoverer} Supported Platform {ROLE_Supported_Platform} Time {ROLE_Time} Vulnerability {ROLE_Vulnerability} Vulnerable System {ROLE_Vulnerable_System} Vulnerable System Owner {ROLE_Vulnerable_System_Owner} Vulnerable System Version {ROLE_Vulnerable_System_Version}",
            "valid roles": ['CVE', 'Capabilities', 'Discoverer', 'Supported_Platform', 'Time', 'Vulnerability', 'Vulnerable_System', 'Vulnerable_System_Owner', 'Vulnerable_System_Version'],
        },
        "Vulnerability-related:PatchVulnerability": {
            "event type": "Vulnerability-related:PatchVulnerability",
            "keywords": [],
            "event description": "Releaser releases Patch for Vulnerable_System at Time in Place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "CVE {ROLE_CVE} Issues Addressed {ROLE_Issues-Addressed} Patch {ROLE_Patch} Patch Number {ROLE_Patch-Number} Releaser {ROLE_Releaser} Supported Platform {ROLE_Supported_Platform} Time {ROLE_Time} Vulnerability {ROLE_Vulnerability} Vulnerable System {ROLE_Vulnerable_System} Vulnerable System Version {ROLE_Vulnerable_System_Version}",
            "valid roles": ['CVE', 'Issues-Addressed', 'Patch', 'Patch-Number', 'Releaser', 'Supported_Platform', 'Time', 'Vulnerability', 'Vulnerable_System', 'Vulnerable_System_Version'],
        },
    },
}
event_type_tags = {
    "phee": {
        "Adverse_event": "Adverse Event",
        "Potential_therapeutic_event": "Potential Therapeutic Event", 
    },
    "casie": {
        "Attack:Databreach": "Attack Databreach",
        "Attack:Phishing": "Attack Phishing",
        "Attack:Ransom": "Attack Ransom",
        "Vulnerability-related:DiscoverVulnerability": "Vulnerability-Related Discover Vulnerability",
        "Vulnerability-related:PatchVulnerability": "Vulnerability-Related Patch Vulnerability",
    },
}

role_type_tags = {
    "phee": {
        "Combination_Drug": "Combination Drug",
        "Effect": "Effect",
        "Subject": "Subject",
        "Subject_Age": "Subject Age",
        "Subject_Disorder": "Subject Disorder",
        "Subject_Gender": "Subject Gender",
        "Subject_Population": "Subject Population",
        "Subject_Race": "Subject Race",
        "Treatment": "Treatment",
        "Treatment_Disorder": "Treatment Disorder",
        "Treatment_Dosage": "Treatment Dosage",
        "Treatment_Drug": "Treatment Drug",
        "Treatment_Duration": "Treatment Duration",
        "Treatment_Freq": "Treatment Freq",
        "Treatment_Route": "Treatment Route",
        "Treatment_Time_elapsed": "Treatment Time Elapsed",
    },
    "casie": {
        "Attack-Pattern": "Attack Pattern",
        "Attacker": "Attacker",
        "CVE": "CVE",
        "Capabilities": "Capabilities",
        "Compromised-Data": "Compromised Data",
        "Damage-Amount": "Damage Amount",
        "Discoverer": "Discoverer",
        "Issues-Addressed": "Issues Addressed",
        "Number-of-Data": "Number of Data",
        "Number-of-Victim": "Number of Victim",
        "Patch": "Patch",
        "Patch-Number": "Patch Number",
        "Payment-Method": "Payment Method",
        "Place": "Place",
        "Price": "Price",
        "Purpose": "Purpose",
        "Releaser": "Releaser",
        "Supported_Platform": "Supported Platform",
        "Time": "Time",
        "Tool": "Tool",
        "Trusted-Entity": "Trusted Entity",
        "Victim": "Victim",
        "Vulnerability": "Vulnerability",
        "Vulnerable_System": "Vulnerable System",
        "Vulnerable_System_Owner": "Vulnerable System Owner",
        "Vulnerable_System_Version": "Vulnerable System Version",
    },
}
